Fix: доработать после тесто в GitHub
DmitrySheyko/java-filmorate pull request #2
Opened 2022-08-03 13:41 UTC by DmitrySheyko

2022-08-04 08:00 UTC, Frilock requested changes
Добрый день, в целом все ок, поправьте только комментарий в pom файле.

2022-08-04 08:00 UTC, Frilock commented on pom.xml
> +			<version>1.18.24</version>
Версии библиотек, которые вы подключаете в pom файле, принято указывать в properties, по аналогии с версией Java, а в поле version самой библиотеки указывать так ${simple-lib.version}. Это нужно для того, чтобы версии библиотек находились в одном месте и их изменении проходило безболезненно.

2022-08-04 08:00 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    static FilmController filmController;
А почему модификаторы не используете?

2022-08-04 13:06 UTC, DmitrySheyko commented on pom.xml
> +			<version>1.18.24</version>
Исправил POM файл, перенес версии библиотек в properties

2022-08-04 13:07 UTC, DmitrySheyko commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    static FilmController filmController;
Добавил модификатры. Изначально домал, что в тестовый файлах они излишни.

2022-08-05 09:03 UTC, Frilock approved these changes
Принято

2022-08-15 15:53 UTC, merged