Add friends likes
DmitrySheyko/java-filmorate pull request #3
Opened 2022-08-19 10:57 UTC by DmitrySheyko

Название — добавлены изменения в соответсвиес ТЗ спринта 10
    Исходная ветка — add-friends-likes
    Целевая ветка — main.

2022-08-20 08:50 UTC, Frilock requested changes
Добрый день, в целом все хорошо, пара комментариев, в основном с вопросами к Вам. Жду новую итерацию.

2022-08-20 08:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +    private String error;
Я так понимаю вы копировали класс из примера, но там указано 2 поля, error и description, а зачем делать структуру состоящую из одного поля? В чем практическая польза от такой структуры вместо использования обычной строки?

2022-08-20 08:50 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean equals(Object o) {
Какие то странные equals и hashCode. Вообще в аннотации Data эти методы включены, но если вы хотите чтоб проверялись не все поля, вы можете убрать Data, повесить нужные Вам аннотации, а в аннотации equalsAndHashCode в параметрах указать exclude поля

2022-08-20 08:50 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Не оставляйте заккоментированный код, он у вас в истории гита сохраниться. Нужно будет по истории восстановите

2022-08-21 09:22 UTC, DmitrySheyko commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ErrorResponse.java
> +    private String error;
Внес изменения. Теперь, при выбрасывании исключений, вместо объекта класса ErrorRespose, передается String.

2022-08-21 09:22 UTC, DmitrySheyko commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public boolean equals(Object o) {
Внес изменения. Убрал переопределенные методы Equals и HashCode. Взамен, прописал аннотацию
@EqualsAndHashCode(of = { ... }) с указанием полей, которые должны учитываться в Equals и HashCode. 
Для проверки работы нам предоставлен набор тестов в Postman. Исходя из тестов, правильным считается варинт классов User и Film в котых для формирования Equals и HashCode используется только поле id. Остальные поля могут быть изменены при выполнении эндпоинта Update

2022-08-21 09:22 UTC, DmitrySheyko commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +//package ru.yandex.practicum.filmorate.controller;
Закомментированный текст убрал

2022-08-21 19:02 UTC, Frilock approved these changes
Принято

2022-08-28 11:48 UTC, merged