Add database
DmitrySheyko/java-filmorate pull request #4
Opened 2022-09-17 20:53 UTC by DmitrySheyko

Название — проект Filmorate доработан по требованиям ТЗ 12.
    Описание — подключена база H2. Сщзданы классы пакета storage.
    Исходная ветка — add-database.
    Целевая ветка — main.

2022-09-18 11:19 UTC, Frilock requested changes
Добрый день, в целом работа как всегда хорошая. Из предложений/пожеланий это вынести мапперы в отдельный слой в приложении. Так в нем будет проще ориентироваться и упростит сами классы хранилищ. 
Кроме того, предложил Вам создать набор абстракций (интерфейсов или абстрактных классов) в которых будут общие методы для ваших контроллеров, сервисов и хранилищ.

2022-09-18 11:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Вообще у Ваших сервисов (как и у контроллеров, как и у хранилищ) есть общая часть методов, по идее в таких случаях логичнее сделать некий абстрактный класс или интерфейс и объявить эти методы там, а тут от него наследоваться или имплементировать

2022-09-18 11:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            stmt.setString(1, newFilm.getName());
Вообще можно сделать отдельный слой в приложении который будет заниматься маппингом.
Например, 
public class UserMapper implements RowMapper<User> {

где нужно переопределить метод 
@Override
    public User mapRow(ResultSet resultSet, int rowNum) throws SQLException {

2022-09-18 11:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +    private Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException {
Лучше в отдельный класс вынести, чтобы был отдельный слой для мапперов

2022-09-18 11:19 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        if (checkIsUserInStorage(userId)) {
В данном случае, вы делаете дополнительный блок if - else, только для того, чтобы определить какого пользователя нет и какой из id бросить в исключении. На мой взгляд, это усложняет код и в данном случае вы можете просто создать две Boalean переменных в них получить значение через вызов метода checkIsUserInStorage, затем в 1 if проверить оба условия и в случае ошибки через тернарник нужный идентификатор бросить указать в исключении.

2022-09-18 15:11 UTC, DmitrySheyko commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        if (checkIsUserInStorage(userId)) {
Выполнил. Спасибо за интересное предложение.

2022-09-18 15:57 UTC, DmitrySheyko commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +            stmt.setString(1, newFilm.getName());
Все Mappers вынесены в отдельный пакет и имплементируют RowMapper.

2022-09-19 13:28 UTC, DmitrySheyko commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
Создал интеофейсы и вынес в них общую часть кода. Для объектов Mpa  и Genres получилась очень стройная структура. Для  Film и User получилось не так красиво из-за обилия разнообразных уникальных методов: добавление лаков, друщей и т.д.

2022-09-19 17:48 UTC, Frilock approved these changes
Принято

2022-09-29 17:01 UTC, merged